### ISSUE TITLE
Prop Logic missing to apply @submit="generatePdf" for JsonEditor component 

### ISSUE THREAD

**Issue by Chrisdalbano** [Chrisdalbano/hastecv#1]
The Homeview component adds  property function to `<ResumeForm @submit="generatePdf" />`, HomeView listens to a submit event from the ResumeForm directly to call generatePdf, the issue arises to child relation since ResumeForm is importing JsonEditor. 

```
   <div v-if="view === 'json'">
      <JsonEditor />
    </div>
```

JsonEditor is out of the scope to execute` generatePdf()`, so to generate a pdf you need to `submitJson()`, this will pass the props to the store and then generate the pdf using the core parent form in ResumeForm.

**Comment by Seevt** [comment]
Resolved on global store logic refactor
